// <auto-generated />
using System;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20240915000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Backend.Domain.IncomePeriod", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateOnly>("PeriodEndDate")
                .HasColumnType("date");

            b.Property<DateOnly>("PeriodStartDate")
                .HasColumnType("date");

            b.Property<decimal>("StartingBalance")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId", "PeriodStartDate", "PeriodEndDate");

            b.ToTable("IncomePeriods");
        });

        modelBuilder.Entity("Backend.Domain.LedgerTransaction", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<string>("Category")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateOnly>("Date")
                .HasColumnType("date");

            b.Property<string>("Kind")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<string>("Note")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<Guid?>("RecurringRuleId")
                .HasColumnType("uuid");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId", "Date");

            b.ToTable("Transactions");
        });

        modelBuilder.Entity("Backend.Domain.RecurringRule", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<string>("Category")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<DateOnly?>("EndDate")
                .HasColumnType("date");

            b.Property<string>("Frequency")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<bool>("IsActive")
                .HasColumnType("boolean");

            b.Property<string>("Note")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<string>("RuleKind")
                .IsRequired()
                .HasMaxLength(40)
                .HasColumnType("character varying(40)");

            b.Property<DateOnly>("StartDate")
                .HasColumnType("date");

            b.Property<string>("Title")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.HasIndex("UserId", "IsActive", "StartDate");

            b.ToTable("RecurringRules");
        });

        modelBuilder.Entity("Backend.Domain.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(320)
                .HasColumnType("character varying(320)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Email")
                .IsUnique();

            b.ToTable("Users");
        });

        modelBuilder.Entity("Backend.Domain.UserSettings", b =>
        {
            b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            b.Property<string>("CurrencyCode")
                .IsRequired()
                .HasMaxLength(8)
                .HasColumnType("character varying(8)");

            b.Property<int>("PaydayDayOfMonth")
                .HasColumnType("integer");

            b.Property<string>("Timezone")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<DateTime>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("UserId");

            b.ToTable("UserSettings");
        });

        modelBuilder.Entity("Backend.Domain.UserSettings", b =>
        {
            b.HasOne("Backend.Domain.User", "User")
                .WithOne("Settings")
                .HasForeignKey("Backend.Domain.UserSettings", "UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("User");
        });

        modelBuilder.Entity("Backend.Domain.User", b =>
        {
            b.Navigation("Settings");
        });
    }
}
